### ISSUE TITLE
Thanks for irtt

### ISSUE THREAD

**Issue by StevenLeRoux** [peteheist/irtt#18]
Hi, This library is a great work and this issue is mostly here to thank you for it.

I would also want to discuss if you would welcome a PR to simplify a few bits?
For example, we could make use of viper/cobra for the CLI, define custom types in structs, etc. 

Would you be open to this idea?

**Comment by heistp** [comment]
Great, glad if you can make use of it!

I wouldn't switch to using viper/cobra for the CLI because of the size of these libraries. One of my goals is to keep the irtt executable as small as possible. It's already larger than I'd like, and if I simply import cobra and viper and call `cobra.OnInitialize(initConfig)`, the resulting (Mach-O) executable almost triples in size from 4673544 bytes to 13099852 bytes.

That was the reason I rolled my own command stuff, although, I know it could be cleaner. :) There's an assortment of refactoring I'd like to get to, probably before accepting external refactoring, so there isn't duplicate work or overlapping intents.

**Comment by StevenLeRoux** [comment]
Alright :) Closing.
